# Numpy

In [2]:
import numpy as np

### Lets do some basic stuff!

In [3]:
a = np.array(5)

In [4]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3, 5)
2
15
int32


In [7]:
b = a.reshape(3,5,1)
b

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

In [8]:
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(3, 5, 1)
3
15
int32


In [9]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### some operations

In [11]:
a = np.array([20 , 30, 40, 50])
b = np.arange(4)

In [12]:
b

array([0, 1, 2, 3])

In [13]:
a - b

array([20, 29, 38, 47])

In [16]:
c = a * b
c

array([  0,  30,  80, 150])

In [17]:
c > 50

array([False, False,  True,  True])

In [18]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])